// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  article_grid: dynamic(() => import("./ArticleGrid")),
  hero: dynamic(() => import("./Hero")),
  project_grid: dynamic(() => import("./ProjectGrid")),
  separator: dynamic(() => import("./Separator")),
};
